apiVersion: v1
kind: Service
metadata:
  name: alfred
  namespace: alfred
  labels:
    app.kubernetes.io/name: alfred
spec:
  selector:
    app.kubernetes.io/name: alfred
  ports:
    - name: http
      port: 8080
      targetPort: http

