apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alfred-serviceaccount.yaml
  - alfred-clusterrole-readonly.yaml
  - alfred-clusterrolebinding.yaml
  - alfred-deployment.yaml
  - alfred-service.yaml
