apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base-podmonitor

labels:
  - pairs:
      release: kube-prometheus-stack
      app.kubernetes.io/part-of: alfred
