apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alfred-staging

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: staging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alfred-config
    files:
      - config.yml

secretGenerator:
  - name: alfred-secrets
    envs:
      - secret.env

patches:
  - path: patch-clusterrolebinding.yaml
