apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alfred-secrets
  namespace: alfred
  labels:
    app.kubernetes.io/name: alfred
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: replace-me
  target:
    name: alfred-secrets
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: replace-me/alfred
        property: ANTHROPIC_API_KEY
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: replace-me/alfred
        property: TELEGRAM_BOT_TOKEN
    - secretKey: PROMETHEUS_TOKEN_PROD_AP
      remoteRef:
        key: replace-me/alfred
        property: PROMETHEUS_TOKEN_PROD_AP

